#<#ConfigForBootstrap2_FollowingSteps.ps1#>
#Create a vhd for a windows image
Diskpart
Create vdisk file=C:\VHD\test.vhd maximum=25000 type=expandable
    Select vdisk file=C:\VHD\test.vhd
    attach vdisk
    Create partition primary
    assign letter=G
    format quick FS=NTFS label=VHD
exit

#Apply the windows image to the vhd
imagex /apply F:\sources\install.wim 5 G:\

#Move and rename the compiled localhost.mof to MetaConfig.mof (autodetected filename)
#C:\Test\PullClientBootstrap\localhost.meta.mof is generated by IISInstall located in <#ConfigForBootstrap2.ps1#>

Move-Item -Path "C:\Test\PullClientBootstrap\localhost.meta.mof" -Destination "G:\Windows\System32\Configuration\MetaConfig.mof"

#Dismount to remove direct access to the vhd content
Dismount-VHD -Path "C:\VHD\test.vhd"

#Create a VM and mount the existing VHD
$newvm = new-vm -Name "TESTSERVERVM" -MemoryStartupBytes 2GB -Generation 2 -Switchname "LANSwitch"
add-vmharddiskdrive -vmname $newvm -Path "C:\VHD\test.vhd"

#After initial boot-up and operating system installation the system will look to the assigned pull server for config
