#<#ConfigForBootstrap_FollowingSteps.ps1#>
#Create a vhd for a windows image
Diskpart
Create vdisk file=C:\VHD\test.vhd maximum=25000 type=expandable
    Select vdisk file=C:\VHD\test.vhd
    attach vdisk
    create partition primary
    assign letter=G
    format quick FS=NTFS label=VHD
exit

#Apply the windows image to the vhd
#F:\sources\install.wim can be downloaded from Microsoft website
#5 is the image5
#Deploying to G:\ drive
imagex /apply F:\sources\install.wim 5 G:\

#move and rename the compiled localhost.mof to Pending.mof (autodetected filename)
#C:\Test\IISInstall\localhost.mof is generated by <#ConfigForBootstrap.ps1#>
#move localhost.mof to G:\ drive & name as Pending.mof

Move-Item -Path C:\Test\IISInstall\localhost.mof -Destination G:\Windows\System32\Configuration\Pending.mof

#Dismount to remove direct access to the vhd content
Dismount-VHD -Path "C:\VHD\test.vhd"

#Create a VM and mount the existing VHD
$newvm = new-vm -Name "TESTServerVM" -MemoryStartupBytes 2GB -Generation 2 -Switchname "LANSwitch"
add-vmharddiskdrive -vmname $newvm -path "C:\VHD\test.vhd"

#After initial boot-up and operating system installation the system will look to the assigned pull server for config
